# Generated by Django 3.1.6 on 2021-02-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='partner/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('YT', 'YOU TUBE'), ('TT', 'TIK TOK'), ('TG', 'TELEGRAM'), ('INST', 'ISTAGRAM')], max_length=250)),
                ('sub_count', models.IntegerField(default=0)),
                ('url', models.URLField()),
                ('price', models.IntegerField(default=0)),
                ('cateegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.category')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partner.partner')),
            ],
        ),
    ]
