# Generated by Django 3.1.6 on 2021-02-10 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20210210_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetwork',
            name='cateegory',
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_network', to='partner.category'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='name',
            field=models.CharField(choices=[('YT', 'YOU TUBE'), ('TT', 'TIK TOK'), ('TG', 'TELEGRAM'), ('INST', 'INSTAGRAM')], max_length=250),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='price',
            field=models.CharField(max_length=250),
        ),
    ]
